In [1]:
import numpy as np

In [2]:
numpyArray = np.arange(1000000)
pyList = list(range(1000000))

In [3]:
%time for _ in range(100): numpyArray *= 2

Wall time: 48 ms


In [4]:
%time for _ in range(100): pyList = [x*2 for x in pyList]

Wall time: 13.6 s


In [5]:
km = np.array([5,6,8,1])
km = np.loadtxt("data/carros-km.txt")

In [6]:
anos = np.loadtxt("data/carros-anos.txt", dtype = int)

In [7]:
km_media = km / (2021 - anos)

In [8]:
km_media.dtype

dtype('float64')

In [9]:
idade = 2021-anos

In [10]:
idade

array([18, 30, 31,  2, 15,  9,  2, 12, 11, 10, 19, 14, 20,  2, 12,  5,  9,
        2,  5,  4, 19,  2, 27, 30,  2,  2,  5,  2, 19, 30, 24, 26,  3, 30,
        7, 26,  2,  2, 12,  2,  8, 18,  2, 19,  2, 19, 17, 20,  2, 18, 12,
       15, 21, 15, 11, 27, 14,  2,  2,  2,  2,  2,  4, 10, 20, 25,  2, 27,
        2, 14, 27, 14, 24, 15,  8, 27, 13, 13,  2,  2, 22, 14, 28, 26,  2,
        2,  5, 10,  2, 19,  8,  4,  5, 13,  3, 18, 18, 17, 11,  2, 15, 20,
        2,  6,  3,  4, 29, 20, 28, 26, 18,  7, 13,  8,  2,  4,  2,  2, 15,
        6, 14, 16,  4, 23,  2, 22,  2, 12, 18, 27,  2, 27,  2,  6, 25, 24,
       28,  2, 29, 26,  2, 31,  2,  2, 30, 31,  9, 14,  8, 21, 19, 25, 25,
        6, 28,  8,  8, 12,  2,  2, 19, 24, 23, 17, 25,  6,  5, 16, 22, 26,
       28, 17,  8, 23,  3,  2,  3,  2, 31, 12, 31, 15, 19, 30, 29,  2,  2,
       16, 11,  2,  5,  2, 11, 27, 20,  7, 25, 28, 28, 20,  2,  2,  2, 14,
        2,  5,  7,  2,  6,  6, 25, 19, 16, 26, 22, 16,  2, 24, 31, 20,  8,
        2,  4, 10, 16, 14

In [11]:
dados = np.array([km, anos])

In [12]:
dados

array([[4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
        1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
        1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
        1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
        1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
        0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
        3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
        4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
        9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
        9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
        8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
        8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
        9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00

In [13]:
dados.shape

(2, 258)

In [14]:
km_media = dados[0]/(2021 - dados[1])

In [15]:
km_media

array([2.46722222e+03, 1.90400000e+02, 1.19751613e+03, 0.00000000e+00,
       1.71713333e+03, 1.19200000e+03, 0.00000000e+00, 6.46658333e+03,
       9.01790909e+03, 3.79780000e+03, 6.76789474e+02, 5.75142857e+02,
       4.48865000e+03, 0.00000000e+00, 3.45475000e+03, 2.31214000e+04,
       5.16100000e+03, 0.00000000e+00, 7.41720000e+03, 3.79325000e+03,
       5.32594737e+03, 0.00000000e+00, 3.63255556e+03, 3.43196667e+03,
       0.00000000e+00, 0.00000000e+00, 1.15900000e+03, 0.00000000e+00,
       3.09726316e+03, 3.14603333e+03, 1.25679167e+03, 2.05123077e+03,
       5.90666667e+03, 1.12693333e+03, 1.29548571e+04, 1.69134615e+03,
       0.00000000e+00, 0.00000000e+00, 4.60500000e+02, 0.00000000e+00,
       1.16768750e+04, 2.26455556e+03, 0.00000000e+00, 4.54221053e+03,
       0.00000000e+00, 5.13421053e+02, 4.11441176e+03, 1.19750000e+02,
       0.00000000e+00, 4.46383333e+03, 7.12950000e+03, 3.36640000e+03,
       3.22457143e+03, 6.26313333e+03, 3.21318182e+03, 3.00025926e+03,
      